### ISSUE TITLE
Add style to navbar

### ISSUE THREAD

**Issue by lkito** [Gogotchuri/GoFast#12]
**Is your feature or change request related to a problem? Please describe.**
The navbar doesn't have a styling

**Describe the solution you'd like**
One file needs to be changed: resources/views/partials/MainNav.vue

Just add a basic styling black background is prefered.

**Comment by enqidu** [comment]
I can work on it. I have some experience in navbar so I think I could handle this.

**Comment by lkito** [comment]
Resolved by #16
