### ISSUE TITLE
Front Endpoint for password forgotten and reset

### ISSUE THREAD

**Issue by Gogotchuri** [Gogotchuri/GoFast#3]
We have implemented password forgotten and reset on backend but we yet to implement it on the front-end in Vue. So, it's not of much of a value.

1) Password forgotten should give user a form, with just an email field and submit(reset) buttom. Form should be posted to corresponding route ( "/api/forgot-password") and display success regardless email exists or not.
2) Password reset should give user, with a password, password confirmation fields and submit(reset) buttom. Form should be posted to corresponding route ( "/api/password-reset"). (!important) post should contain field token with valid token, extracted from url.

**Comment by shotanozadze** [comment]
I will fix it

**Comment by lkito** [comment]
Resolved by #7
