### ISSUE TITLE
Email Verification Front End-Point

### ISSUE THREAD

**Issue by Gogotchuri** [Gogotchuri/GoFast#4]
We have implemented **email verification** feature on backend but we yet to implement it on the front-end in Vue. So, it's not of much of a value.

We need a page for authorized user, where sent code can be entered and submitted to the backend.

**Comment by lkito** [comment]
### Possible Implementation

Three files need to be changed in total:
1. resources/views/auth/EmailVerification.vue - View for the page
2. resources/views/partials/MainNav.vue - Need to add a button redirecting to the verification page
3. resources/js/modules/auth/routes.module.js - Need to add route to the verification page

**Comment by durid17** [comment]
I will take it , if that's not a problem

**Comment by lkito** [comment]
Resolved by #11
