### ISSUE TITLE
Featue: Implement a pagination service

### ISSUE THREAD

**Issue by lkito** [Gogotchuri/GoFast#8]
### Explain the Proposed Feature or Change
Add a pagination service for ease of access.

### Possible Implementation
One file will need to be changed: app/services/pagination/paginator.go

Structures have already been written and the fields are self-explanatory. Function needs to be implemented

**Comment by gdara17** [comment]
I'll take this one ;)

**Comment by lkito** [comment]
Resolved by pull request #14
